"""add user_id column

Revision ID: 524421783939
Revises:
Create Date: 2025-08-06 10:13:52.631548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "524421783939"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=True))
#     op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'])
#     # ### end Alembic commands ###


def upgrade():
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_todos_user_id", "users", ["user_id"], ["id"]  # 외래키 이름 필수
        )


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, "todos", type_="foreignkey")
#     op.drop_column("todos", "user_id")
#     # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.drop_constraint("fk_todos_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")
